### ISSUE TITLE
Adding extra more buttons to your version?

### ISSUE THREAD

**Issue by LeoMegaAir** [dcpedit/kinesismod#1]
Hi dcpedit, I'm new to all this so please bear with me.

_This is not an issue_, it's a question but I couldn't find a way to ask a question here. My Kinesis has seven extra buttons (the original Kinesis controller has some extra lines so [all people do it](https://geekhack.org/index.php?topic=36195.msg2252517#msg2252517)). 

Would it be possible to retain those extra buttons if I get rid of the original controller and use yours?
Another question would be, the [blackpill folder](https://github.com/dcpedit/kinesismod/tree/master/blackpill) contains so many files - which of them am I supposed to use to order a PCB on JLCPCB?

**Comment by dcpedit** [comment]
The [kinesismod_blackpill.zip](https://github.com/dcpedit/kinesismod/blob/master/blackpill/kinesismod_blackpill.zip) is the file you'll want to upload to JLCPCB.

As for the extra buttons, theoretically you can get them to work, but you will need to wire them up correctly.  There's room in the matrix for extra keys, so you'll can use the unused slots, but make sure the row pin is connected to a diode.  See the firmware source files for how the matrix is wired:

https://github.com/dcpedit/vial-qmk-dev/blob/vial/keyboards/dcpedit/kint_bp/kint_bp.h

Pin assignments:

https://github.com/dcpedit/vial-qmk-dev/blob/vial/keyboards/dcpedit/kint_bp/config.h
